### The Business Problem

Our client is a credit card company. They have brought us a dataset that includes some demographics and recent financial data (the past six months) for a sample of 30,000 of their account holders. This data is at the credit account level; in other words, there is one row for each account (you should always clarify what the definition of a row is, in a dataset). Rows are labeled by whether in the next month after the six month historical data period, an account owner has defaulted, or in other words, failed to make the minimum payment.

### Goal
Your goal is to develop a predictive model for whether an account will default next month, given demographics and historical data


### Data Exploration Steps 

1. How many columns are there in the data?These may be features, response, or metadata.
2. How many rows (samples)?
3. What kind of features are there? Which are categorical and which are numerical?
Categorical features have values in discrete classes such as "Yes," "No," or "maybe." Numerical features are typically on a continuous numerical scale, such as dollar amounts.
4. What does the data look like in these features?To see this, you can examine the range of values in numeric features, or the frequency of different classes in categorical features, for example
5. Is there any missing data?

In [1]:
# import libraries
import pandas as pd

In [2]:
df = pd.read_excel('../data/default_of_credit_card_clients.xls')

In [3]:
df.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE PAY_1  PAY_2  \
0  798fc410-45c1      20000    2          2         1   24     2      2   
1  8a8c8f3b-8eb4     120000    2          2         2   26    -1      2   
2  85698822-43f5      90000    2          2         2   34     0      0   
3  0737c11b-be42      50000    2          2         1   37     0      0   
4  3b7f77cc-dbc0      50000    1          2         1   57    -1      0   

   PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0     -1     -1  ...          0          0          0         0       689   
1      0      0  ...       3272       3455       3261         0      1000   
2      0      0  ...      14331      14948      15549      1518      1500   
3      0      0  ...      28314      28959      29547      2000      2019   
4     -1      0  ...      20940      19146      19131      2000     36681   

   PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0         0         0         0         0                           1  
1      1000      1000         0      2000                           1  
2      1000      1000      1000      5000                           0  
3      1200      1100      1069      1000                           0  
4     10000      9000       689       679                           0  

[5 rows x 25 columns]

### Verifying Basic Data Integrity

In [4]:
# examining column names
df.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_1',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object')

### Meta  Data
1. The account ID column is referenced as ID
2. LIMIT_BAL - Amount of the credit provided (in New Taiwanese (NT) dollar) including individual consumer credit and the family (supplementary) credit
3. SEX: Gender (1 = male; 2 = female)
4. EDUCATION: Education (1 = graduate school; 2 = university; 3 = high school; 4 = others). 
5. MARRIAGE: Marital status (1 = married; 2 = single; 3 = others). 
6. AGE: Age (year). 
7. PAY_1–Pay_6: A record of past payments. Past monthly payments, recorded from April to September, are stored in these columns. 
8. PAY_1 represents the repayment status in September; PAY_2 = repayment status in August; and so on up to PAY_6, which represents the repayment status in April. The measurement scale for the repayment status is as follows: -1 = pay duly; 1 = payment delay for one month; 2 = payment delay for two months; and so on up to 8 = payment delay for eight months; 9 = payment delay for nine months and above. 
9. BILL_AMT1–BILL_AMT6: Bill statement amount (in NT dollar). 
10. BILL_AMT1 represents the bill statement amount in September; BILL_AMT2represents the bill statement amount in August; and so on up to BILL_AMT7, which represents the bill statement amount in April. 
11. PAY_AMT1–PAY_AMT6: Amount of previous payment (NT dollar). PAY_AMT1 represents the amount paid in September; PAY_AMT2 represents the amount paid in August; and so on up to PAY_AMT6, which represents the amount paid in A

In [5]:
#  target column (ID) and count unique values

df['ID'].nunique()

29687

In [6]:
# How many rows and columns?
df.shape

# number of unique IDs is less than the number of rows. This implies that the ID is not a unique identifier

(30000, 25)

In [7]:
# Store the value counts in a variable defined as id_counts
id_counts = df['ID'].value_counts()

In [8]:
# display stored values
id_counts.head()

feac3745-a2be    2
742d1d93-0d3b    2
310d5326-56c7    2
b3c9d09b-ed59    2
e850d228-6879    2
Name: ID, dtype: int64

In [9]:
# Display the number of grouped duplicated entries
id_counts.value_counts()

# Most IDs occur exactly once, as expected. However, 313 IDs occur twice.

1    29374
2      313
Name: ID, dtype: int64

### Boolean Masks (Logical Mask)

A logical mask is a way to filter an array, or series, by some condition. For example, we can use the "is equal to" operator in Python, ==, to find all locations of an array that contain a certain value. Other comparisons, such as "greater than" (>), "less than" (<), "greater than or equal to" (>=), and "less than or equal to" (<=), can be used similarly. The output of such a comparison is an array or series of True/False values, also known as Boolean values. Each element of the output corresponds to an element of the input, is True if the condition is met, and is False otherwise.

In [10]:
# import numpy
import numpy as np

In [11]:
# generate random numbers using seed
np.random.seed(seed=24)

#  generate 100 random integers, chosen from between 1 and 5 (inclusive)
random_integers = np.random.randint(low=1,high=5,size=100)

In [12]:
random_integers

array([3, 4, 1, 4, 2, 2, 2, 1, 4, 4, 1, 4, 4, 3, 4, 4, 4, 4, 4, 4, 2, 3,
       4, 4, 2, 4, 2, 4, 1, 1, 3, 1, 4, 2, 2, 1, 4, 3, 2, 2, 3, 3, 2, 3,
       4, 2, 3, 4, 1, 3, 4, 2, 2, 4, 1, 2, 3, 3, 2, 1, 2, 4, 2, 1, 4, 3,
       1, 2, 1, 3, 4, 2, 3, 4, 1, 3, 2, 1, 1, 3, 3, 4, 3, 2, 4, 1, 4, 4,
       4, 4, 1, 4, 3, 2, 4, 4, 3, 3, 2, 4])

In [13]:
# locations of all elements of random_integers equal to 3
is_equal_to_3 = random_integers == 3
is_equal_to_3[:10]

array([ True, False, False, False, False, False, False, False, False,
       False])

In [14]:
#  how many elements were equal to 3
sum(is_equal_to_3)

22

In [15]:
# select the elements of the original array that meet that condition
random_integers[is_equal_to_3]

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [16]:
# using the dataset

# display the first 5 duplicated IDS 

dupe_mask = id_counts ==2
dupe_mask[0:5]

feac3745-a2be    True
742d1d93-0d3b    True
310d5326-56c7    True
b3c9d09b-ed59    True
e850d228-6879    True
Name: ID, dtype: bool

In [17]:
# Access the index of id_count and display the first five rows
id_counts.index[0:5]

Index(['feac3745-a2be', '742d1d93-0d3b', '310d5326-56c7', 'b3c9d09b-ed59',
       'e850d228-6879'],
      dtype='object')

In [18]:
# Select and store the duplicated IDs in a new variable called dupe_ids
dupe_ids = id_counts.index[dupe_mask]

In [19]:
# Convert dupe_ids to a list and then obtain the length of the list
dupe_ids = list(dupe_ids)
len(dupe_ids)

313

In [20]:
# verify the data in dupe_ids by displaying the first five
dupe_ids[0:5]

['feac3745-a2be',
 '742d1d93-0d3b',
 '310d5326-56c7',
 'b3c9d09b-ed59',
 'e850d228-6879']

Look at the values of the features, to see what, if anything, might be different between these duplicate entries.

use the .isin and .loc methods for this purpose

In [21]:
df.loc[df['ID'].isin(dupe_ids[0:3]),:].head(10) 

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE PAY_1  PAY_2  \
12424  feac3745-a2be     220000    1          3         2   30     0      0   
12524  feac3745-a2be          0    0          0         0    0     0      0   
24849  742d1d93-0d3b     310000    1          1         2   32    -2     -2   
24949  742d1d93-0d3b          0    0          0         0    0     0      0   
26811  310d5326-56c7     100000    1          2         2   28    -1     -1   
26911  310d5326-56c7          0    0          0         0    0     0      0   

       PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
12424     -1     -1  ...       5036       8269       3681      1066      4723   
12524      0      0  ...          0          0          0         0         0   
24849     -2     -2  ...       8639      12862       4553     32617     17417   
24949      0      0  ...          0          0          0         0         0   
26811     -1     -1  ...        390          0        780       390       390   
26911      0      0  ...          0          0          0         0         0   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
12424      5051      8293      3692      3087                           0  
12524         0         0         0         0                           0  
24849      8702     12926      4575      1990                           0  
24949         0         0         0         0                           0  
26811       390         0       780         0                           0  
26911         0         0         0         0                           0  

[6 rows x 25 columns]

In [22]:
#  Boolean matrix of the same size as the entire DataFrame using ==, 

df_zero_mask = df == 0
df_zero_mask

ID  LIMIT_BAL    SEX  EDUCATION  MARRIAGE    AGE  PAY_1  PAY_2  \
0      False      False  False      False     False  False  False  False   
1      False      False  False      False     False  False  False  False   
2      False      False  False      False     False  False   True   True   
3      False      False  False      False     False  False   True   True   
4      False      False  False      False     False  False  False   True   
...      ...        ...    ...        ...       ...    ...    ...    ...   
29995  False      False  False      False     False  False   True   True   
29996  False      False  False      False     False  False  False  False   
29997  False      False  False      False     False  False  False  False   
29998  False      False  False      False     False  False  False  False   
29999  False      False  False      False     False  False   True   True   

       PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0      False  False  ...       True       True       True      True     False   
1       True   True  ...      False      False      False      True     False   
2       True   True  ...      False      False      False     False     False   
3       True   True  ...      False      False      False     False     False   
4      False   True  ...      False      False      False     False     False   
...      ...    ...  ...        ...        ...        ...       ...       ...   
29995   True   True  ...      False      False      False     False     False   
29996  False  False  ...      False      False       True     False     False   
29997  False  False  ...      False      False      False      True      True   
29998   True   True  ...      False      False      False     False     False   
29999   True   True  ...      False      False      False     False     False   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0          True      True      True      True                       False  
1         False     False      True     False                       False  
2         False     False     False     False                        True  
3         False     False     False     False                        True  
4         False     False     False     False                        True  
...         ...       ...       ...       ...                         ...  
29995     False     False     False     False                        True  
29996     False     False      True      True                        True  
29997     False     False     False     False                       False  
29998     False     False     False     False                       False  
29999     False     False     False     False                       False  

[30000 rows x 25 columns]

In [23]:
# Boolean series feature_zero_mask

feature_zero_mask = df_zero_mask.iloc[:,1:].all(axis=1)

In [24]:
#  sum of the Boolean series 
sum(feature_zero_mask)

315

In [25]:
# Clean the DataFrame by eliminating the rows with all zeros, except for the ID
df_clean_1 = df.loc[~feature_zero_mask,:].copy()

In [26]:
# verify columns and columns of the cleaned data

df_clean_1.shape

(29685, 25)

In [27]:
# Obtain the number of unique IDs
df_clean_1['ID'].nunique()

29685

In [29]:
# Obtain the data type of the columns in the data by using the .info() 
df_clean_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 29685 entries, 0 to 29999
Data columns (total 25 columns):
ID                            29685 non-null object
LIMIT_BAL                     29685 non-null int64
SEX                           29685 non-null int64
EDUCATION                     29685 non-null int64
MARRIAGE                      29685 non-null int64
AGE                           29685 non-null int64
PAY_1                         29685 non-null object
PAY_2                         29685 non-null int64
PAY_3                         29685 non-null int64
PAY_4                         29685 non-null int64
PAY_5                         29685 non-null int64
PAY_6                         29685 non-null int64
BILL_AMT1                     29685 non-null int64
BILL_AMT2                     29685 non-null int64
BILL_AMT3                     29685 non-null int64
BILL_AMT4                     29685 non-null int64
BILL_AMT5                     29685 non-null int64
BILL_AMT6             

In [31]:
# view the top n rows of the PAY_1
df_clean_1['PAY_1'].head()

0     2
1    -1
2     0
3     0
4    -1
Name: PAY_1, dtype: object

In [33]:
#  value counts for the PAY_1 column by using .value_counts()
df_clean_1['PAY_1'].value_counts()

0                13087
-1                5047
1                 3261
Not available     3021
-2                2476
2                 2378
3                  292
4                   63
5                   23
8                   17
6                   11
7                    9
Name: PAY_1, dtype: int64